################################################################################
#
# DinguxCommander
#
################################################################################

COMMANDER_VERSION = 7ea0831
COMMANDER_SITE = $(call github,od-contrib,commander,$(COMMANDER_VERSION))
COMMANDER_DEPENDENCIES = sdl sdl_gfx sdl_image sdl_ttf

COMMANDER_TARGET_PLATFORM ?= $(call qstrip,$(BR2_PACKAGE_COMMANDER_TARGET_PLATFORM))

ifeq ($(BR2_TARGET_PLATFORM),"rg350")
COMMANDER_TARGET_PLATFORM=rg350
else ifeq ($(BR2_TARGET_PLATFORM),"gcw0")
COMMANDER_TARGET_PLATFORM=gcw0
else ifeq ($(BR2_TARGET_PLATFORM),"retrofw")
COMMANDER_TARGET_PLATFORM=rs90
else ifeq ($(BR2_TARGET_PLATFORM),"retrofw")
COMMANDER_TARGET_PLATFORM=retrofw
else
$(error No platform mapping for $(BR2_TARGET_PLATFORM))
endif

COMMANDER_CONF_OPTS += \
	-DTARGET_PLATFORM=$(COMMANDER_TARGET_PLATFORM) \
	-DWITH_SYSTEM_SDL_TTF=ON \
	-DWITH_SYSTEM_SDL_GFX=ON

ifneq ($(BR2_PACKAGE_COMMANDER_AUTOSCALE),"")
COMMANDER_CONF_OPTS += -DAUTOSCALE=$(BR2_PACKAGE_COMMANDER_AUTOSCALE)
endif

ifneq ($(BR2_PACKAGE_COMMANDER_PPU_X),"")
COMMANDER_CONF_OPTS += -DPPU_X=$(BR2_PACKAGE_COMMANDER_PPU_X)
endif

ifneq ($(BR2_PACKAGE_COMMANDER_PPU_Y),"")
COMMANDER_CONF_OPTS += -DPPU_Y=$(BR2_PACKAGE_COMMANDER_PPU_Y)
endif

ifneq ($(BR2_PACKAGE_COMMANDER_WIDTH),"")
COMMANDER_CONF_OPTS += -DSCREEN_WIDTH=$(BR2_PACKAGE_COMMANDER_WIDTH)
endif

ifneq ($(BR2_PACKAGE_COMMANDER_HEIGHT),"")
COMMANDER_CONF_OPTS += -DSCREEN_HEIGHT=$(BR2_PACKAGE_COMMANDER_HEIGHT)
endif

ifeq ($(BR2_PACKAGE_COMMANDER_OPK_NAME),"")
COMMANDER_OPK_NAME = commander-$(COMMANDER_TARGET_PLATFORM)
else
COMMANDER_OPK_NAME = $(BR2_PACKAGE_COMMANDER_OPK_NAME)
endif

define COMMANDER_INSTALL_TARGET_CMDS
	mkdir -p $(BINARIES_DIR)/opks
	cd $(@D) && ./package-opk.sh $(COMMANDER_TARGET_PLATFORM) $(COMMANDER_BUILDDIR) \
	  $(BINARIES_DIR)/opks/$(COMMANDER_OPK_NAME).opk
endef

$(eval $(cmake-package))
